#!/usr/bin/env python3
"""Count distinct central maps generated by fold stacks on an s x s block (all families, all sequences)."""
import sys
from itertools import product
from w1_foldstack import FAM


def maps(s):
    out = set()
    cells = [(x, y) for x in range(s) for y in range(s)]
    for (a, b), dA, dB in FAM:
        f = lambda p: a * p[0] + b * p[1]
        lv = sorted({f(p) for p in cells}); levels = list(range(lv[0] - 1, lv[-1] + 1))
        for seq in product((dA, dB), repeat=len(levels)):
            c = dict(zip(levels, seq))
            out.add(tuple(frozenset({(-c[f(p) - 1][0], -c[f(p) - 1][1]), c[f(p)]}) for p in cells))
    return out


if __name__ == '__main__':
    s = int(sys.argv[1]); print(f'{s}x{s}: {len(maps(s))} distinct fold-stack maps')
