"""Build MENU.md from menu_results.jsonl: best gadget per (edge type, pairing class)."""
import json, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'w-integrator'))
from strands import parity
rows = [json.loads(l) for l in open('menu_results.jsonl')]
best = {}
for r in rows:
    if r.get('rate') is None or not r.get('check', {}).get('paths_ok'): continue
    k = (r['kind'], r['rule'] + (' [passes filter vs %s, shifts:strands %s]' % (r['vs'], r.get('accept')) if r.get('vs') else ''))
    r = dict(r, rule=k[1])
    key = (r['rate'], r['status'] != 'OPTIMAL', r['D'], r['P'])
    if k not in best or key < best[k][0]: best[k] = (key, r)
infeas = {}
for r in rows:
    if r['status'] == 'INFEASIBLE':
        infeas.setdefault((r['kind'], r['rule']), []).append('P%d D%d' % (r['P'], r['D']))
out = ['# Edge gadget MENU (KT Edge Searcher, lane-free and per pairing class)', '',
       'Generated by w-searcher/make_menu.py from menu_results.jsonl. Date of runs: see "stamp" in the jsonl (2026-10-02).',
       'Model: kt/strip.py band (bottom: P columns x D rows; left: D columns x Q rows), line family x+2y=c outside.',
       'Constraints: degree 2, no finite cycle, no winding strand, every line end joined to another line end,',
       'and (if a class is given) every strand joins lines c<c\' with (c mod M, c\'-c) in the allowed set.',
       'rate = crossings per column (bottom) or per row (left). "OPTIMAL" = optimal for THAT period P and depth D (CP-SAT).',
       'pairing = list of (c mod cper, d) meaning pair {c, c+d}; cper = P (bottom) or 2Q (left); local line c = x+2y in the template frame.',
       'pi = matching parity (w-integrator/strands.py parity, shift 0, sign +1).',
       'Every template passed the independent unrolled check (w-searcher/verify.py: degrees, all paths end at line ends, crossings).', '']
for kind in ('left', 'bottom'):
    out.append('## %s edge' % kind); out.append('')
    out.append('| class | rate | status | P | D | pi | pairing | template |')
    out.append('|---|---|---|---|---|---|---|---|')
    items = sorted([v[1] for k, v in best.items() if k[0] == kind], key=lambda r: (r['rate'], r['rule']))
    for r in items:
        pr = [tuple(p) for p in r['pairing']]
        pi = parity([(a, a + d) for a, d in pr], r['cper'])
        tpl = ' / '.join(r['tpl']) if len(' '.join(r['tpl'])) < 400 else '(see menu_results.jsonl)'
        out.append('| %s | %.4g | %s%s | %d | %d | %d | %s | `%s` |' % (r['rule'], r['rate'], r['status'],
                   '' if r['status'] == 'OPTIMAL' else ' (bound %.4g/unit)' % (r['bound'] / r['P']) if r.get('bound') is not None else '',
                   r['P'], r['D'], pi, ' '.join('%d+%d' % p for p in pr), tpl))
    out.append('')
    inf = sorted((k[1], v) for k, v in infeas.items() if k[0] == kind and k not in best)
    if inf:
        out.append('Classes with no gadget found (INFEASIBLE at all tried sizes): ' + '; '.join('%s [%s]' % (a, ', '.join(b)) for a, b in inf))
        out.append('')
open('MENU.md', 'w').write('\n'.join(out) + '\n')
print('\n'.join(out))
