"""Cutting-plane LP for a linear side potential h(s) = sum_k w_k [slot k in s] (see corner_pot.py).
max z  s.t.  z <= cost_j + w.phi_j (corner solutions j, generated by CP-SAT),  S*c + h(u) - h(v) >= 0 (strip arcs,
generated by stripzi streaming check).  Final claim needs: corner OPTIMAL at integer w (presolve off) AND stripzi
min reduced cost >= 0 for the same integer w.  Then R_W(n) >= 4 * corner value for all n >= 2A.
usage: potlp.py W A prefix [tl_corner] [B]   (prefix: stripzi output prefix holding _zarcs.txt; work files <prefix>_pot*)"""
import sys, subprocess, json, os, time
from fractions import Fraction
from math import lcm
import numpy as np
from scipy.optimize import linprog
import corner_pot as cp
W, A, pre = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
TL = float(sys.argv[4]) if len(sys.argv) > 4 else 600; B = float(sys.argv[5]) if len(sys.argv) > 5 else 6
HERE = os.path.dirname(os.path.abspath(__file__))
S = cp.slots_of(W); K = len(S)
chi = lambda m: np.array([(m >> k) & 1 for k in range(K)], dtype=float)
arcs = []  # (chi(v)-chi(u), c)
if os.path.exists(pre + '_zarcs.txt'):
    seen = set()
    for line in open(pre + '_zarcs.txt'):
        u, v = (int(t, 16) for t in line.split()); d = tuple(chi(v) - chi(u))
        if d not in seen: seen.add(d); arcs.append((np.array(d), 0))
sols = []; log = open(pre + f'_potlp_A{A}.log', 'a')
def say(*a):
    s = ' '.join(str(x) for x in a); print(s, flush=True); log.write(s + '\n'); log.flush()
say('start', time.strftime('%F %T'), 'W', W, 'A', A, 'K', K, 'zero-arc rows', len(arcs))
def lp():
    # variables w (K), z ; minimize -z
    Aub, bub = [], []
    for phi, c in sols: Aub.append(list(-np.array(phi, dtype=float)) + [1.0]); bub.append(c)
    for d, c in arcs: Aub.append(list(d) + [0.0]); bub.append(c)
    res = linprog(np.r_[np.zeros(K), -1.0], A_ub=np.array(Aub), b_ub=np.array(bub),
                  bounds=[(-B, B)] * K + [(-50, 50)], method='highs')
    return res.x[:K], res.x[K]
def to_int(w):
    fr = [Fraction(x).limit_denominator(24) for x in w]; sc = 1
    for f in fr: sc = lcm(sc, f.denominator)
    return [int(f * sc) for f in fr], sc
w_int, sc = [0] * K, 1
best = None
for it in range(400):
    if sols:
        w, z = lp(); w_int, sc = to_int(w)
    else: z = 50
    st, val, bd, new = cp.solve(W, A, w_int, sc, TL)
    for c, phi in new: sols.append((phi, c))
    say(f'it {it} LP z {z:.4f} scale {sc} corner {st} value {val/sc:.4f} bound {bd/sc:.4f} sols {len(sols)}')
    if st != 'OPTIMAL': say('corner not optimal; stop'); break
    if val / sc < z - 1e-6: continue
    # corner value matches the LP: check strip validity of this integer w
    wf = pre + f'_pot_A{A}_w.txt'; open(wf, 'w').write(f'{sc} ' + ' '.join(map(str, w_int)) + '\n')
    if os.environ.get('REMOTE'):   # REMOTE=user@host:dir  (dir holds stripzi and <W>/states: z<W>/z<W>_states.bin)
        host, rdir = os.environ['REMOTE'].split(':')
        subprocess.run(['scp', '-q', wf, f'{host}:{rdir}/potw.txt'], check=True)
        cmd = (f'cd {rdir} && ulimit -v 8000000 && WFILE=potw.txt STATES=z{W}/z{W}_states.bin OMP_NUM_THREADS=4 '
               f'nice -n 19 ./stripzi {W} z{W}/chk && echo VIOLFILE && cat z{W}/chk_viol.txt')
        out = subprocess.run(['ssh', host, cmd], capture_output=True, text=True).stdout
        head, _, vtxt = out.partition('VIOLFILE\n'); open(pre + '_chk_viol.txt', 'w').write(vtxt); out = head
    else:
        env = dict(os.environ, WFILE=wf)
        if os.path.exists(pre + '_states.bin'): env['STATES'] = pre + '_states.bin'
        out = subprocess.run([os.path.join(HERE, 'stripzi'), str(W), pre + '_chk'], env=env, capture_output=True, text=True).stdout
    line = [l for l in out.splitlines() if l.startswith('scale')][0]; say('  strip check:', line)
    mr = int(line.split()[5])
    if mr >= 0:
        say(f'VALID potential, corner OPTIMAL {val/sc}: R_W(n) >= {4*val/sc} for n >= {2*A}; w = {sc} {w_int}')
        best = (val / sc, sc, w_int)
        break
    nv = 0
    for l in open(pre + '_chk_viol.txt'):
        u, v, c, _ = l.split(); u, v = int(u, 16), int(v, 16); arcs.append((chi(v) - chi(u), int(c))); nv += 1
    say('  added violated arcs', nv)
json.dump({'best': best, 'nsols': len(sols), 'narcs': len(arcs)}, open(pre + f'_potlp_A{A}.json', 'w'))
