// band.cpp - transfer-matrix solver for a periodic band between two knight-line fields
// (KT Edge Searcher, 2026-10-02). Lane-free: degree 2 in the band, no finite cycle.
// Optional: colour-current target. Gives the minimum crossing rate over ALL periods (rigorous
// lower bound: infinite strands / two-strand "winding pairs" are allowed, as a relaxation) and a
// witness cycle (check it independently).
//
// Input (generated by band_gen.py):
//   PA MAXDA COLS_PER_UNIT
//   M00 M01 M10 M11            scaled real coordinates (X,Y) = M (a,b), a = sweep, b = depth
//   for r = 0..PA-1:  n  then n lines: b chi nfix (da db)*nfix      cells of columns a = r mod PA
//   NM then NM lines: da db     forward knight moves (da > 0) in (a,b) coordinates
// Model: band cells have degree 2; a cell's fixed edges (to the outside line fields) are given;
// other edges join two band cells. Crossings: proper crossings among band edges and fixed edges.
// Current: flux through the cut between columns t and t+1, F = sum over band edges straddling the
// cut of chi(lower-a end), normalised to the cut after a column with a = 0 (mod PA):
//   current(t) = F(t) - sum_{t'=1..t} sum_{cells c in column t'} chi(c) (2 - nfix(c)).
// usage: band input.txt [target_current|none] [maxstates]
#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

int PA, MAXDA, CPU;
int M00, M01, M10, M11;
struct Cell { int b, chi, nfix; vector<pair<int, int>> fix; };
vector<vector<Cell>> col;               // per residue
vector<pair<int, int>> FM;              // forward moves
int NM;

static int orient(ll ax, ll ay, ll bx, ll by, ll cx, ll cy) { ll v = (bx - ax) * (cy - ay) - (by - ay) * (cx - ax); return (v > 0) - (v < 0); }
static bool segX(ll a1, ll b1, ll a2, ll b2, ll c1, ll d1, ll c2, ll d2) {   // (a,b) coordinates
    ll X1 = M00 * a1 + M01 * b1, Y1 = M10 * a1 + M11 * b1, X2 = M00 * a2 + M01 * b2, Y2 = M10 * a2 + M11 * b2;
    ll X3 = M00 * c1 + M01 * d1, Y3 = M10 * c1 + M11 * d1, X4 = M00 * c2 + M01 * d2, Y4 = M10 * c2 + M11 * d2;
    return orient(X1, Y1, X2, Y2, X3, Y3) * orient(X1, Y1, X2, Y2, X4, Y4) < 0 && orient(X3, Y3, X4, Y4, X1, Y1) * orient(X3, Y3, X4, Y4, X2, Y2) < 0;
}
int res(int a) { return ((a % PA) + PA) % PA; }
int cellIdx(int a, int b) { auto& v = col[res(a)]; for (int i = 0; i < (int)v.size(); i++) if (v[i].b == b) return i; return -1; }
const Cell* cellAt(int a, int b) { int i = cellIdx(a, b); return i < 0 ? nullptr : &col[res(a)][i]; }

// pending edge: source (c+off, b), move m; label lab: -1 = T (strand from a terminal / unknown past), >= 0 partner index
struct PE { int off, b, m, lab; };
struct St { int ph; vector<PE> e; };
string enc(const St& s) { string k; k.push_back((char)s.ph); for (auto& p : s.e) { k.push_back((char)p.off); k.push_back((char)p.b); k.push_back((char)p.m); k.push_back((char)p.lab); } return k; }
St dec(const string& k) { St s; s.ph = k[0]; for (size_t i = 1; i < k.size(); i += 4) s.e.push_back({(signed char)k[i], (signed char)k[i + 1], (signed char)k[i + 2], (signed char)k[i + 3]}); return s; }

// static crossing counts with fixed edges, per (residue, b, m); fixed-fixed per residue
map<tuple<int, int, int>, int> crossFcache;
int crossF(int r, int b, int m) {
    auto key = make_tuple(r, b, m); auto it = crossFcache.find(key); if (it != crossFcache.end()) return it->second;
    int a2 = r + FM[m].first, b2 = b + FM[m].second, cnt = 0;
    for (int a = r - 2 * MAXDA - 2; a <= r + 2 * MAXDA + 2; a++) for (auto& c : col[res(a)]) for (auto& f : c.fix)
        cnt += segX(r, b, a2, b2, a, c.b, a + f.first, c.b + f.second);
    return crossFcache[key] = cnt;
}
vector<int> crossFF;   // per residue: fixed-fixed crossings assigned to the column of the lower-indexed edge

int main(int argc, char** argv) {
    setvbuf(stdout, NULL, _IONBF, 0);
    if (argc < 2) { fprintf(stderr, "usage: band input [target|none] [maxstates]\n"); return 1; }
    FILE* f = fopen(argv[1], "r");
    if (fscanf(f, "%d %d %d", &PA, &MAXDA, &CPU) != 3) return 1;
    if (fscanf(f, "%d %d %d %d", &M00, &M01, &M10, &M11) != 4) return 1;
    col.resize(PA);
    for (int r = 0; r < PA; r++) {
        int n; if (fscanf(f, "%d", &n) != 1) return 1;
        for (int i = 0; i < n; i++) {
            Cell c; if (fscanf(f, "%d %d %d", &c.b, &c.chi, &c.nfix) != 3) return 1;
            for (int j = 0; j < c.nfix; j++) { int da, db; if (fscanf(f, "%d %d", &da, &db) != 2) return 1; c.fix.push_back({da, db}); }
            col[r].push_back(c);
        }
    }
    if (fscanf(f, "%d", &NM) != 1) return 1;
    for (int i = 0; i < NM; i++) { int da, db; if (fscanf(f, "%d %d", &da, &db) != 2) return 1; FM.push_back({da, db}); }
    fclose(f);
    bool useTarget = argc > 2 && string(argv[2]) != "none";
    int target = useTarget ? atoi(argv[2]) : 0;
    long maxStates = argc > 3 ? atol(argv[3]) : 30000000;
    // fixed-fixed crossings per residue (pairs counted once: edge with smaller (a, b, dir) owns it)
    crossFF.assign(PA, 0);
    for (int r = 0; r < PA; r++) for (auto& c : col[r]) for (auto& fe : c.fix)
        for (int a = r; a <= r + 2 * MAXDA + 4; a++) for (auto& c2 : col[res(a)]) for (auto& fe2 : c2.fix) {
            auto k1 = make_tuple(r, c.b, fe.first, fe.second), k2 = make_tuple(a, c2.b, fe2.first, fe2.second);
            if (!(k1 < k2)) continue;
            crossFF[r] += segX(r, c.b, r + fe.first, c.b + fe.second, a, c2.b, a + fe2.first, c2.b + fe2.second);
        }
    // current normalisation G(t) for cuts t = 0..PA-1 (cut after column t); G(0) = 0
    vector<int> G(PA + 1, 0);
    for (int t = 1; t <= PA; t++) { int s = 0; for (auto& c : col[res(t)]) s += c.chi * (2 - c.nfix); G[t] = G[t - 1] + s; }
    if (G[PA] != 0) fprintf(stderr, "warning: G(PA) = %d != 0\n", G[PA]);
    // state current: state with next column c = ph has cut t = ph - 1
    auto current = [&](const St& s) {
        int F = 0;
        for (auto& p : s.e) { const Cell* c = cellAt(s.ph + p.off, p.b); F += c->chi; }
        int t = res(s.ph - 1);
        return F - G[t];
    };
    // ---- transitions ----
    auto trans = [&](const St& s, auto&& cb) {
        int c = s.ph; const auto& cells = col[c];
        int nc = cells.size();
        vector<vector<int>> inc(nc);
        map<pair<int, int>, int> fut;     // future cell (aoff, b) -> incoming count
        for (int i = 0; i < (int)s.e.size(); i++) {
            auto& p = s.e[i]; int ta = p.off + FM[p.m].first, tb = p.b + FM[p.m].second;
            if (ta == 0) { int ci = cellIdx(c, tb); if (ci < 0) return; inc[ci].push_back(i); }
            else fut[{ta, tb}]++;
        }
        for (int ci = 0; ci < nc; ci++) if ((int)inc[ci].size() + cells[ci].nfix > 2) return;
        // DFS over cells
        vector<pair<int, int>> chosen;   // (cell idx, move)
        int baseX = crossFF[c];
        function<void(int, int)> dfs = [&](int ci, int X) {
            if (ci == nc) {
                // connectivity: nodes = old pending edges 0..n-1, new edges n.., T nodes
                int n = s.e.size(), nn = chosen.size();
                int NN = n + nn + 2 * nc + 2 * n + 4;
                vector<vector<int>> adj(NN);          // incident link ids
                vector<pair<int, int>> L;               // links
                vector<char> isT(NN, 0);
                int tn = n + nn;
                auto link = [&](int u, int v) { adj[u].push_back(L.size()); adj[v].push_back(L.size()); L.push_back({u, v}); };
                for (int i = 0; i < n; i++) {
                    if (s.e[i].lab < 0) { isT[tn] = 1; link(i, tn); tn++; }
                    else if (i < s.e[i].lab) link(i, s.e[i].lab);
                }
                for (int ci2 = 0; ci2 < nc; ci2++) {
                    vector<int> items;
                    for (int i : inc[ci2]) items.push_back(i);
                    for (int j = 0; j < nn; j++) if (chosen[j].first == ci2) items.push_back(n + j);
                    for (int k = 0; k < cells[ci2].nfix; k++) { isT[tn] = 1; items.push_back(tn++); }
                    if (items.size() != 2) { fprintf(stderr, "degree bug\n"); exit(1); }
                    link(items[0], items[1]);
                }
                vector<char> visL(L.size(), 0);
                auto walk = [&](int st0) {   // from a degree-1 node to the other end
                    int u = st0, e = adj[u][0];
                    while (true) {
                        visL[e] = 1; int v = L[e].first == u ? L[e].second : L[e].first;
                        if (adj[v].size() == 1) return v;
                        int e2 = adj[v][0] == e ? adj[v][1] : adj[v][0]; u = v; e = e2;
                    }
                };
                St t; t.ph = res(c + 1);
                vector<int> nodeOf;   // nodes that become pending in the new state, in order
                for (int i = 0; i < n; i++) if (s.e[i].off + FM[s.e[i].m].first > 0) nodeOf.push_back(i);
                for (int j = 0; j < nn; j++) nodeOf.push_back(n + j);
                // build new pending list sorted
                vector<pair<array<int, 3>, int>> lst;
                for (int nd : nodeOf) {
                    array<int, 3> key;
                    if (nd < n) key = {s.e[nd].off - 1, s.e[nd].b, s.e[nd].m};
                    else key = {-1, cells[chosen[nd - n].first].b, chosen[nd - n].second};
                    lst.push_back({key, nd});
                }
                sort(lst.begin(), lst.end());
                map<int, int> posOf; for (int i = 0; i < (int)lst.size(); i++) posOf[lst[i].second] = i;
                vector<int> lab(lst.size(), -2);
                for (int i = 0; i < (int)lst.size(); i++) {
                    int nd = lst[i].second;
                    if (lab[i] != -2) continue;
                    if (adj[nd].size() != 1) { fprintf(stderr, "end degree bug %zu\n", adj[nd].size()); exit(1); }
                    int o = walk(nd);
                    if (o == nd) { fprintf(stderr, "walk bug\n"); exit(1); }
                    if (isT[o]) lab[i] = -1;
                    else { int j = posOf.at(o); lab[i] = j; lab[j] = i; }
                }
                // T nodes walking to T nodes: complete strands; mark visited
                for (int u = n + nn; u < tn; u++) if (adj[u].size() == 1 && !visL[adj[u][0]]) walk(u);
                for (size_t e = 0; e < L.size(); e++) if (!visL[e]) return;   // cycle
                for (int i = 0; i < (int)lst.size(); i++) t.e.push_back({lst[i].first[0], lst[i].first[1], lst[i].first[2], lab[i]});
                cb(t, X + baseX, chosen);
                return;
            }
            const Cell& cl = cells[ci];
            int need = 2 - (int)inc[ci].size() - cl.nfix;
            for (int msk = 0; msk < (1 << NM); msk++) {
                if (__builtin_popcount(msk) != need) continue;
                bool ok = true; int dX = 0;
                vector<pair<int, int>> tg;
                for (int m = 0; m < NM && ok; m++) if (msk >> m & 1) {
                    int ta = FM[m].first, tb = cl.b + FM[m].second;
                    const Cell* tc = cellAt(c + ta, tb);
                    if (!tc) { ok = false; break; }
                    int cur = fut.count({ta, tb}) ? fut[{ta, tb}] : 0;
                    if (cur + 1 + tc->nfix > 2) { ok = false; break; }
                    tg.push_back({ta, tb});
                    dX += crossF(c, cl.b, m);
                    // vs pending edges spanning past column c
                    for (auto& p : s.e) { int pa2 = p.off + FM[p.m].first; if (pa2 <= 0) continue; dX += segX(0, cl.b, ta, tb, p.off, p.b, pa2, p.b + FM[p.m].second); }
                    for (auto& ch : chosen) { int b0 = cells[ch.first].b; dX += segX(0, cl.b, ta, tb, 0, b0, FM[ch.second].first, b0 + FM[ch.second].second); }
                    for (int m2 = 0; m2 < m; m2++) if (msk >> m2 & 1) dX += segX(0, cl.b, ta, tb, 0, cl.b, FM[m2].first, cl.b + FM[m2].second);
                }
                if (!ok) continue;
                for (auto& q : tg) fut[q]++;
                size_t sz = chosen.size();
                for (int m = 0; m < NM; m++) if (msk >> m & 1) chosen.push_back({ci, m});
                dfs(ci + 1, X + dX);
                chosen.resize(sz);
                for (auto& q : tg) if (--fut[q] == 0) fut.erase(q);
            }
        };
        dfs(0, 0);
    };
    unordered_map<string, int> id; vector<string> keys; vector<vector<pair<int, int>>> G2;
    auto getId = [&](const St& s) { string k = enc(s); auto it = id.find(k); if (it != id.end()) return it->second; int n = keys.size(); id[k] = n; keys.push_back(k); G2.emplace_back(); return n; };
    vector<int> baseIds;
    if (!getenv("BASE")) { fprintf(stderr, "set BASE=template-edges file\n"); return 1; }
    {
        // base family: replay a periodic template (edges a1 b1 a2 b2, period LT in a) from T labels
        FILE* bf = fopen(getenv("BASE"), "r"); int LT, ne; if (fscanf(bf, "%d %d", &LT, &ne) != 2) return 1;
        vector<array<int, 4>> TE(ne); for (auto& e : TE) if (fscanf(bf, "%d %d %d %d", &e[0], &e[1], &e[2], &e[3]) != 4) return 1;
        fclose(bf);
        if (LT % PA) { fprintf(stderr, "template period not a multiple of PA\n"); return 1; }
        auto mmove = [&](int da, int db) { for (int m = 0; m < NM; m++) if (FM[m].first == da && FM[m].second == db) return m; return -1; };
        auto maskAt = [&](int c) {   // pending edges at the cut before column c, sorted (off, b, m)
            vector<array<int, 3>> v;
            for (auto& e : TE) for (int k = c / LT - 3; k <= c / LT + 3; k++) { int a1 = e[0] + k * LT, a2 = e[2] + k * LT;
                if (a1 < c && c <= a2) { int m = mmove(a2 - a1, e[3] - e[1]); if (m < 0) { fprintf(stderr, "bad template move\n"); exit(1); } v.push_back({a1 - c, e[1], m}); } }
            sort(v.begin(), v.end()); return v;
        };
        St s; s.ph = 0; for (auto& q : maskAt(0)) s.e.push_back({q[0], q[1], q[2], -1});
        int X = 0;
        for (int c = 0; c < 6 * LT; c++) {
            auto want = maskAt(c + 1); bool found = false; St nx; int xx = 0;
            trans(s, [&](const St& t, int Xc, const vector<pair<int, int>>&) {
                if (t.e.size() != want.size()) return;
                for (size_t i = 0; i < want.size(); i++) if (t.e[i].off != want[i][0] || t.e[i].b != want[i][1] || t.e[i].m != want[i][2]) return;
                found = true; nx = t; xx = Xc; });
            if (!found) { fprintf(stderr, "base template not valid at column %d\n", c); return 1; }
            s = nx;
            if (c >= 5 * LT) { X += xx; baseIds.push_back(getId(s)); }
        }
        fprintf(stderr, "base template: %d crossings per %d columns, current %d\n", X, LT, current(s));
    }
    // ---- forward closure from the base family ----
    for (size_t q = 0; q < keys.size(); q++) {
        St s = dec(keys[q]);
        map<int, int> best;
        trans(s, [&](const St& t, int X, const vector<pair<int, int>>&) { int to = getId(t); auto it = best.find(to); if (it == best.end() || it->second > X) best[to] = X; });
        for (auto& kv : best) G2[q].push_back(kv);
        if ((long)keys.size() > maxStates) { printf("{\"status\":\"STATE_LIMIT\"}\n"); return 2; }
        if (q % 500000 == 0) fprintf(stderr, "  q=%zu states=%zu\n", q, keys.size());
    }
    int N = keys.size();
    vector<char> alive(N, 1);
    {   // keep only states that can return to the base family
        vector<vector<int>> pr(N); for (int u = 0; u < N; u++) for (auto& a : G2[u]) pr[a.first].push_back(u);
        vector<char> co(N, 0); deque<int> dq; for (int b : baseIds) if (!co[b]) { co[b] = 1; dq.push_back(b); }
        while (!dq.empty()) { int u = dq.front(); dq.pop_front(); for (int p : pr[u]) if (!co[p]) { co[p] = 1; dq.push_back(p); } }
        int nco = 0; bool nocr = getenv("NOCOREACH") != nullptr;
        for (int u = 0; u < N; u++) { if (!co[u] && !nocr) alive[u] = 0; nco += co[u]; }
        fprintf(stderr, "reachable %d, also co-reachable %d\n", N, nco);
    }
    if (useTarget) for (int u = 0; u < N; u++) if (current(dec(keys[u])) != target) alive[u] = 0;
    // trim
    {
        vector<int> outd(N, 0), ind(N, 0); vector<vector<int>> pred(N);
        for (int u = 0; u < N; u++) if (alive[u]) for (auto& a : G2[u]) if (alive[a.first]) { outd[u]++; ind[a.first]++; pred[a.first].push_back(u); }
        deque<int> dq; for (int u = 0; u < N; u++) if (alive[u] && (!outd[u] || !ind[u])) { alive[u] = 0; dq.push_back(u); }
        while (!dq.empty()) { int u = dq.front(); dq.pop_front();
            for (int p : pred[u]) if (alive[p] && --outd[p] == 0) { alive[p] = 0; dq.push_back(p); }
            for (auto& a : G2[u]) if (alive[a.first] && --ind[a.first] == 0) { alive[a.first] = 0; dq.push_back(a.first); } }
    }
    int NA = 0; for (int u = 0; u < N; u++) NA += alive[u];
    fprintf(stderr, "states %d core %d\n", N, NA);
    if (getenv("CURHIST")) { map<int, pair<int, int>> h; for (int u = 0; u < N; u++) { int c = current(dec(keys[u])); h[c].first++; if (alive[u]) h[c].second++; } for (auto& kv : h) fprintf(stderr, "  current %d: states %d core %d\n", kv.first, kv.second.first, kv.second.second); }
    if (!NA) { printf("{\"status\":\"NO_CYCLE\",\"states\":%d}\n", N); return 0; }
    // Howard
    typedef long double LD; const LD eps = 1e-9;
    vector<int> pol(N, -1); vector<LD> eta(N), xv(N);
    for (int u = 0; u < N; u++) if (alive[u]) { int bj = -1; for (int j = 0; j < (int)G2[u].size(); j++) if (alive[G2[u][j].first] && (bj < 0 || G2[u][j].second < G2[u][bj].second)) bj = j; pol[u] = bj; }
    for (int it = 0; it < 100000; it++) {
        vector<int> color(N, 0), path;
        for (int s0 = 0; s0 < N; s0++) if (alive[s0] && !color[s0]) {
            path.clear(); int u = s0;
            while (!color[u]) { color[u] = 1; path.push_back(u); u = G2[u][pol[u]].first; }
            if (color[u] == 1) {
                LD sum = 0; int len = 0, v = u; do { sum += G2[v][pol[v]].second; len++; v = G2[v][pol[v]].first; } while (v != u);
                LD e = sum / len; vector<int> cyc; v = u; do { cyc.push_back(v); v = G2[v][pol[v]].first; } while (v != u);
                eta[u] = e; xv[u] = 0; color[u] = 2;
                for (int i = cyc.size() - 1; i >= 1; i--) { int w = cyc[i]; eta[w] = e; xv[w] = G2[w][pol[w]].second - e + xv[G2[w][pol[w]].first]; color[w] = 2; }
            }
            for (int i = path.size() - 1; i >= 0; i--) { int w = path[i]; if (color[w] == 2) continue; int nx = G2[w][pol[w]].first; eta[w] = eta[nx]; xv[w] = G2[w][pol[w]].second - eta[nx] + xv[nx]; color[w] = 2; }
        }
        bool ch = false;
        for (int u = 0; u < N; u++) if (alive[u]) { int bj = pol[u]; LD be = eta[G2[u][bj].first]; for (int j = 0; j < (int)G2[u].size(); j++) { int v = G2[u][j].first; if (alive[v] && eta[v] < be - eps) { be = eta[v]; bj = j; } } if (bj != pol[u]) { pol[u] = bj; ch = true; } }
        if (!ch) for (int u = 0; u < N; u++) if (alive[u]) { int bj = pol[u]; LD bv = G2[u][bj].second - eta[u] + xv[G2[u][bj].first];
            for (int j = 0; j < (int)G2[u].size(); j++) { int v = G2[u][j].first; if (!alive[v] || fabsl(eta[v] - eta[u]) > eps) continue; LD val = G2[u][j].second - eta[u] + xv[v]; if (val < bv - eps) { bv = val; bj = j; } }
            if (bj != pol[u]) { pol[u] = bj; ch = true; } }
        if (!ch) break;
    }
    int bu = -1; for (int u = 0; u < N; u++) if (alive[u] && (bu < 0 || eta[u] < eta[bu])) bu = u;
    { vector<char> seen(N, 0); int u = bu; while (!seen[u]) { seen[u] = 1; u = G2[u][pol[u]].first; } bu = u; }
    vector<int> cyc; { int u = bu; do { cyc.push_back(u); u = G2[u][pol[u]].first; } while (u != bu); }
    ll sumC = 0; for (int u : cyc) sumC += G2[u][pol[u]].second; int L = cyc.size();
    // certificate: no cycle with mean < sumC/L among alive states (SPFA on w*L - sumC)
    bool cert = true;
    { vector<ll> d(N, 0); vector<char> inq(N, 0); vector<int> cnt(N, 0); deque<int> q;
      for (int u = 0; u < N; u++) if (alive[u]) { q.push_back(u); inq[u] = 1; }
      while (!q.empty() && cert) { int u = q.front(); q.pop_front(); inq[u] = 0;
        for (auto& a : G2[u]) if (alive[a.first]) { ll w = (ll)a.second * L - sumC; if (d[u] + w < d[a.first]) { d[a.first] = d[u] + w;
            if (!inq[a.first]) { if (++cnt[a.first] > NA + 1) { cert = false; break; } q.push_back(a.first); inq[a.first] = 1; } } } } }
    // witness edges
    printf("{\"status\":\"%s\",\"states\":%d,\"core\":%d,\"cycle_len\":%d,\"cost\":%lld,\"rate_per_col\":%.6f,\"rate_per_unit\":%.6f,\"target\":\"%s\",\"phase0\":%d,\"edges\":[",
           cert ? "CERTIFIED" : "UNCERTIFIED", N, NA, L, sumC, (double)sumC / L, (double)sumC / L * CPU, useTarget ? argv[2] : "none", dec(keys[cyc[0]]).ph);
    bool first = true;
    for (int i = 0; i < L; i++) {
        St s = dec(keys[cyc[i]]); int to = G2[cyc[i]][pol[cyc[i]]].first, want = G2[cyc[i]][pol[cyc[i]]].second; bool found = false;
        trans(s, [&](const St& t, int X, const vector<pair<int, int>>& ch) {
            if (found || X != want || id[enc(t)] != to) return; found = true;
            for (auto& e : ch) { int b = col[s.ph][e.first].b; printf("%s[%d,%d,%d,%d]", first ? "" : ",", i, b, i + FM[e.second].first, b + FM[e.second].second); first = false; }
        });
        if (!found) { fprintf(stderr, "reconstruct failed\n"); return 3; }
    }
    printf("],\"currents\":[");
    for (int i = 0; i < L; i++) printf("%s%d", i ? "," : "", current(dec(keys[cyc[i]])));
    printf("]}\n");
    return 0;
}
