#!/usr/bin/env python3
"""B5f (KT Lower Bounds, 2026-10-03): geometry tables for b5f.cpp, from Structures' / Verifier's own definitions
(claim38_switch.qs = tile quarters, claim9_tiles.proper = proper crossing), so that J matches c5j_patch.py exactly.
Slot id = ((ly + 2) * 6 + lx) * 4 + m, lower cell (lx, ly), ly in -2..0, move m of UPM; frame row 0 = current row.
Pseudo-slots 72, 73 = the fixed ports (4,0)-(6,1), (5,0)-(7,1) of the U boundary."""
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / 'w-verifier')); sys.path.insert(0, str(ROOT / 'gap/verifier'))
from claim38_switch import edge, qs
from claim9_tiles import proper
UPM = [(2, 1), (-2, 1), (1, 2), (-1, 2)]
seg = {}
for ly in (-2, -1, 0):
    for lx in range(6):
        for m, (dx, dy) in enumerate(UPM):
            if 0 <= lx + dx < 6: seg[((ly + 2) * 6 + lx) * 4 + m] = ((lx, ly), (lx + dx, ly + dy))
seg[72] = ((4, 0), (6, 1)); seg[73] = ((5, 0), (7, 1))
N = 74
valid = [int(s in seg) for s in range(N)]
x3 = [[0] * N for _ in range(N)]; ys = [[0] * N for _ in range(N)]; x1q = [[-1] * N for _ in range(N)]; qm = [0] * N
for a in seg:
    ea = edge(*seg[a])
    for q in qs(ea):
        if q[1] == 0 and 0 <= q[0] <= 4: qm[a] |= 1 << (q[0] * 4 + q[2])
    for b in seg:
        if a == b: continue
        eb = edge(*seg[b])
        if not proper(ea, eb): continue
        sh = set(qs(ea)) & set(qs(eb))
        if min(ea[0][0], ea[1][0]) <= 2 and min(eb[0][0], eb[1][0]) <= 2: x3[a][b] = 1
        elif sh and all(q[0] <= 4 for q in sh): ys[a][b] = 1   # BEYOND5 13.8 Y_sh (j_prime.py)
        if len(sh) == 1:
            (qx, qy, k), = sh
            if qy == 0 and 0 <= qx <= 4: x1q[a][b] = qx * 4 + k
out = ['// generated by b5f_tables.py', f'static const int NS = {N};',
       'static const int VALID[NS] = {' + ','.join(map(str, valid)) + '};',
       'static const unsigned QM[NS] = {' + ','.join(map(str, qm)) + '};',
       'static const signed char X3[NS][NS] = {' + ','.join('{' + ','.join(map(str, r)) + '}' for r in x3) + '};',
       'static const signed char YS[NS][NS] = {' + ','.join('{' + ','.join(map(str, r)) + '}' for r in ys) + '};',
       'static const signed char X1Q[NS][NS] = {' + ','.join('{' + ','.join(map(str, r)) + '}' for r in x1q) + '};']
(Path(__file__).parent / 'b5f_tables.h').write_text('\n'.join(out) + '\n')
print('ys pairs', sum(map(sum, ys)) // 2, 'with port 72', sum(ys[72]));print('slots', len(seg), 'x3 pairs', sum(map(sum, x3)) // 2, 'x1 pairs', sum(v >= 0 for r in x1q for v in r) // 2)
